---
- name: Installer mariadb (Debian/Ubuntu)
  apt:
    name: mariadb-server
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Installer mariadb (RedHat/CentOS)
  yum:
    name: mariadb-server
    state: present
  when: ansible_os_family == "RedHat"
